
THING = \
	lots \
	of \
	things \
	sure

install := CONDMACRO = john
install := OTHERTHING += roger

all:	target list
	/bin/true
	test -f something && \
	    do something else
	echo $(THING)

# vim: set syntax=make:
