
THING = \
	lots \
	of \
	things \
	sure

install := CONDMACRO = john
install := OTHERTHING += roger

install2 install3 := TARGET = install

all:	target list
	/bin/true
	test -f something && \
	    do something else
	echo $(THING)

extra targets: depend on me
	echo some
	echo extra
	echo commands


targets:
	more!

# vim: set syntax=make:
